### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Striker2k18** [asklimanov/fifine-k658#1]
Брат, я хз как у тебя он не шумит, но у меня шум просто ужасный, установил твои настройки, но из плагинов поставил только LoudMax64. Спасает только nvidia broadcast с максимумом шумодава, но голос сильно страдает, можешь подсказать как фиксить?

**Comment by asklimanov** [comment]
Фиксить это довольно просто. Несёшь в магазин и меняешь на не бракованный.
